name: arabic_converter
description: A new Flutter project.

publish_to: 'none' 

version: 0.0.1+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  flutter_localizations:
    sdk: flutter

  flutter_markdown: ^0.6.9
  url_launcher: ^6.0.20
  cupertino_icons: ^1.0.2
  open_file: ^3.2.1
  pdf: ^3.7.3
  file_picker: ^4.5.1
  syncfusion_flutter_pdf: ^19.4.56-beta
  universal_io: ^2.0.4
  flutter_launcher_icons: ^0.9.2
  file_saver: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  generate: true 

  fonts:
    - family: Lateef
      fonts:
        - asset: fonts/Lateef-Regular.ttf
  assets:
    - fonts/
  
